{% set name = "libcloudspawner" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libcloudspawner-{{ version }}.tar.gz
  sha256: bea61c63c5eb0b646404ea164a8f50ba36e7af11cde726ee9dab01a0973c4335

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - jupyterhub >=4.0.0
    - apache-libcloud

test:
  imports:
    - libcloudspawner
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupytercloud-project/jupyterhub-libcloudspawner
  summary: JupyterHub Spawner for clouds
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tristanlt
